### ISSUE TITLE
Gradle - gradleBuildCommand - Add Properties

### ISSUE THREAD

**Issue by shruda** [blackducksoftware/hub-detect#142]
https://github.com/blackducksoftware/hub-detect/blob/5ed3f0013d7cd153ee8bac1b627fd1400734efb7/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/GradleBomTool.groovy#L121

Our build.gradle file needs properties (repository credentials) so that the "dependencies" task can be executed. I tried to add them to --detect.gradle.build.command but it doesn't work.

`--detect.gradle.build.command="-PdeploymentPassword=**** -PdeploymentUsername=deployment -PspecificationVersion=16.1.0-SNAPSHOT dependencies"`

Gradle gets the parameters as one argument and therefore this hack doesn't work. From my point of view it works if the parameters will be splitted.

**Comment by ekerwin** [comment]
You are absolutely right - we will fix this in either the next release, or 2.2.0, coming very soon (by the end of the year).

**Comment by ekerwin** [comment]
This PR (not sure when it will release) should address this.

https://github.com/blackducksoftware/hub-detect/pull/157

**Comment by utsavsanghani** [comment]
Let's keep this for 2.3.0 or later. Thank you @shruda & @ekerwin

**Comment by shruda** [comment]
What's the estimated release date for "2.30 or later"? We need this fix for our integration (see IDETECT-391  & case 00074197)

**Comment by ekerwin** [comment]
2.2.0 is now released and this fix is in there. Please close this ticket if you're all set and if not, please let me know what is still wrong.

**Comment by ekerwin** [comment]
I'm assuming all is well - closing.
