### ISSUE TITLE
Java 9 - hub-detect-1.2.0.jar doesn't work

### ISSUE THREAD

**Issue by shruda** [blackducksoftware/hub-detect#144]
hub-detect-1.2.0.jar doesn't work as expected if it will be executed by using Java 9.

**hub-detect.sh output:**
` INFO--- Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@72cc7e6f: startup date [Thu Oct 19 08:00:00 CEST 2017]; root of context hierarchy
 INFO--- Registering beans for JMX exposure on startup
 INFO--- Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@72cc7e6f: startup date [Thu Oct 19 08:00:00 CEST 2017]; root of context hierarchy
 INFO--- Unregistering JMX-exposed beans on shutdown
Result code of 0, exiting`

**Temporary Workaround:**
I execute the shell script on a windows machine and adding a Java 8 installation in front of the current windows path before the execution of hub-detect.sh
set PATH="C:\Program Files\Java\jdk1.8.0_144\bin";%PATH%

**Comment by akamen** [comment]
@shruda we have not tested with Java 9 and cannot claim support.
