### ISSUE TITLE
Add a parameter for Detect Jar location

### ISSUE THREAD

**Issue by baderbuddy** [blackducksoftware/hub-detect#162]
It would be really helpful to be able to specify a parameter for where to download the hub-detect jar from, that way I could reference a local Artifactory instead of downloading over the web. I'd also like a way to avoid the latest-commit-id.txt downloading directly from the web.

**Comment by akamen** [comment]
@baderbuddy  interesting suggestion, we will strongly consider it and look into it for the upcoming version.

**Comment by ekerwin** [comment]
I'd like a little more detail here. You can avoid the latest-commit-id check and all web traffic completely by simply executing the jar file that is in your local Artifactory. You can acquire the jar file in Artifactory with a simple REST call (https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API).

Is it that you want some features of the shell script but not others? You could gain the "latest" version capabilities by simply installing a version-less jar in your Artifactory and just replacing it when we release a new version.

It seems like you just want to avoid the shell script execution which is totally fine. It is merely provided for those who find it useful - hub-detect in no way requires you to run it that way. It can be run as a jar file "java -jar hub-detect.jar".

Can you please help me understand a little bit better what you're after?

**Comment by akamen** [comment]
@baderbuddy  reassigning to you.  If you have no intention to use the shell script, then it would indeed be redundant to add this feature.  @ekerwin  provided a viable solution.
