### ISSUE TITLE
git-describe trimming needs to be refined

### ISSUE THREAD

**Issue by mydimension** [blackducksoftware/hub-detect#237]
https://github.com/blackducksoftware/hub-detect/blob/e1edd3f08fbde5f9b3cc930d83b1ffa293fac1d4/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/go/godep/GoGodepsParser.groovy#L54

the intent here is to convert strings like `v1.0.0-10-gae3452` to `v1.0.0`

however, the current implemention would trounce on a legit tag name like `v1.0.0-alpha-3`

the right pattern to search for and replace is `-\d+-g[0-9a-f]+$` - the anchoring pattern here is the `g` preceding the short commit hash`

**Comment by jamesrichard91** [comment]
@mydimension is it always going to be a '-g? Will we always want to trim the version starting at the '-g'? 
Ex.  v1.0.0-10-gae3452 should this be trimmed to v1.0.0-10 or v1.0.0 ? 
Ex. v1.0.0-gamma-3 should this be trimmed at all?

**Comment by jamesrichard91** [comment]
The code to address this issue has been merged
