### ISSUE TITLE
Hub detect fails to parse python requirements.txt file when using pip v10.0

### ISSUE THREAD

**Issue by gsnyder2007** [blackducksoftware/hub-detect#241]
# Issue template
## Expected behavior
* Hub detect's pip inspector parses the requirements.txt file.
## Actual behavior
* The inspector fails to parse the requirements.txt file.
* This is because in pip 10.0 all the API's got moves to pip._internal.
See https://pip.pypa.io/en/stable/news/ under 10.0.0b1, Deprecations and Removals.
Notice that in pip-inspector.py we use the parse_requirements and PipSession calls which have moved in 10.0. I'm going to propose a fix (in Github) but wanted to record this in case someone else comes across it while we work out how best to fix it.
## Steps to Reproduce
* Install pip 10.x
* Run hub detect with the pip inspector on any (valid) requirements.txt file
## Version
Affects Hub detect v3.2.0 and prior versions

**Language Version:**
Applies to python environments using pip 10.x

**OS:**
I think this issue affects all OS's but I specifically am using OSX (High Sierra)

**Comment by easauceda** [comment]
Thanks @gsnyder2007 for writing this up. I lost half a day debugging this one.

**Comment by jamesrichard91** [comment]
Code has been merged. Closing this issue
