### ISSUE TITLE
Allow to choose which packagers to run

### ISSUE THREAD

**Issue by omerlh** [blackducksoftware/hub-detect#26]
Let's say I have multiple packages files - for example when working on iOS with Cocoapod, you probably have `Podfile`. You might also have `Gemfile` in the same folder, so you could easily install tools like Fastlane. Now, when scanning my iOS project, I want to scan only the `Podfile` - I don't care about the `Gemfile`. It would be nice to be able to specify which scanners to run.

**Comment by jrichardBD** [comment]
The 'detect.bom.tool.type.override' property is what you are looking for. You'll want to add a comma separated list as the value in the property file. The tool types are case sensitive, if you want the full list please look at com.blackducksoftware.integration.hub.detect.type.BomToolType

Ex: detect.bom.tool.type.override=MAVEN,GRADLE,COCOAPODS

**Comment by omerlh** [comment]
Cool, thanks!
