### ISSUE TITLE
Scan Gradle file without building

### ISSUE THREAD

**Issue by omerlh** [blackducksoftware/hub-detect#27]
I think that today in order to scan Gradle files, hub-detect will try first to build them. Why is that? I don't think this is necessary, and it will make things a lot simpler. Also it look like [VersionEye](https://www.versioneye.com/) is able to scan Gradle files without compiling - and it is working pretty good.

**Comment by ekerwin** [comment]
What would you recommend as an alternative? This is the only way we found that is efficient enough for all the cases we want to cover. Using the output from 'gradle dependencies' was not acceptable as we could not get it fast enough with many sub-projects.

VersionEye appears to only parse a single build.gradle file - that is not sufficient for our customers. Unless I'm reading their source incorrectly, they would not handle sub-projects automatically, you'd have to apply their product to each of your build.gradle files.

Hub-Detect is a post-build tool - to keep things as simple and consistent as we can for all customers, we require that any project using Hub-Detect be buildable from the same place you are invoking Hub-Detect.

**Comment by akamen** [comment]
@omerlh, @ekerwin  is largely correct that parsing is insufficient, in addition to reasons stated consider the following:    
1) Unless they invoke Gradle resolution, you will miss transitive components.
2) Unless they invoke Gradle resolution, you will miss all versions that contain ranges or are not explicitly stated in one way or another.

**Comment by omerlh** [comment]
I would agree with what you are saying, if hub-detect were able to run as post build script and not running the build again. For example, in a CI I would like to run it in a different build - so that hub-detect failure will not fail the build. 
BTW, it is good to hear that hub-detect is able to scan sub-projects, this is a really nice feature. Do you have similar support for Nuget? Meaning, scanning all the packages in a solution and not in a single project?

**Comment by ekerwin** [comment]
It doesn't run the build again. By default, it uses the 'dependencies' task. What is your fundamental objection? Is it just a concern over our implementation, or does it have an actual effect on your systems? Hub-Detect should absolutely not fail your build unless you want it to. Is it leaking failures as Exceptions?

In Jenkins (if you are using a different CI, we can try and figure out how to do it there) you would simply invoke hub-detect as a post build action in a shell script task.

**Comment by omerlh** [comment]
My only concern - I want to have clear separation in the CI (in TeamCity, I would like to do it in separate builds in the same projects) so it would make clear why a specific build fails. I do want to fail the build based on scan results, but I would rather use [Glue](https://github.com/OWASP/glue) for that. That's my only objection. And it seems to work - using the artifact from an existing build.

**Comment by ekerwin** [comment]
So you are able to do what you want? In TeamCity, you can just add a new Build Step using SSH Exec, right? If this won't work for you, we will need to understand your issue better.

**Comment by omerlh** [comment]
I think this should work, I will update if not. Thank you!
