### ISSUE TITLE
integration-gradle-inspector-latest.pom does not exist in maven

### ISSUE THREAD

**Issue by kaempke** [blackducksoftware/hub-detect#271]
Moin,

Hub-Detect is not able to find the file 'integration-gradle-inspector-latest.pom' inside Maven. Correct because the folder 'latest' does not exist.

"_Could not GET 'https://repo.maven.apache.org/maven2/com/blackducksoftware/integration/integration-gradle-inspector/latest/integration-gradle-inspector-latest.pom'._"

**Comment by jamesrichard91** [comment]
Yes, Detect should be resolving latest to the correct latest version. In what version of Detect are you seeing this issue? @kaempke

**Comment by kaempke** [comment]
Today again in Version 4.0.3

**Comment by jamesrichard91** [comment]
Please try using --logging.level.com.blackducksoftware.integration=debug. You should see something like "Exception encountered when resolving latest version of Gradle Inspector" followed by a reason

**Comment by akamen** [comment]
@kaempke We assume the fixed worked?
