### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by FarhadKabir** [blackducksoftware/hub-detect#297]
**Black Duck ignoring npm dependencies** 

Our organization have been using BlackDuck for analyzing security and License related issues in npm packages. Recently, we have noticed an issue in blackduck scans. It often misses some dependencies while scanning an npm package. Question here is what can be the reason for ignoring a package dependency in results? 

Operating Systems Produced on:
Windows 10

**Comment by jamesrichard91** [comment]
Do you have an example of dependencies that are being missed? Can you provide steps to reproduce the problem? In what version of Detect were you getting the results you expected? In what version of Detect is this problem occurring?

**Comment by akamen** [comment]
@FarhadKabir  I assume this is no longer an issue.  Please reopen, if not the case.
