### ISSUE TITLE
Use BDS_JAVA_HOME when calling Signature Scanner

### ISSUE THREAD

**Issue by joc0611** [blackducksoftware/hub-detect#325]
## Expected behavior
* When Signature Scanner is invoked, the JVM located at ``BDS_JAVA_HOME`` is used to run Signature Scanner
## Actual behavior
* The Oracle JVM included in ``scan.cli.zip`` is used
## Steps to Reproduce
* Given ``JAVA_HOME`` is set, ``export BDS_JAVA_HOME=${JAVA_HOME}``
* Call ``hub-detect.sh``
## Version
**Project Version: 4.2.1**
**OS: Alpine Linux**

## Fix

This is fixed in ``hub-common`` starting with version 38.2.0, so this issue can be fixed by updating the depency to ``hub-detect``. Once ``hub-common`` is released, I can provide a PR if that helps.

**Comment by joc0611** [comment]
Once hub-detect is released, I can provide a PR if that is helps.

**Comment by akamen** [comment]
Thank you @joc0611 for following this through.  Looping in @ekerwin to make sure we are on top of things.

**Comment by joc0611** [comment]
AFAICS, the updated hub-common version is already used in master as of 45b6555. Thanks! Do you guys consider this as fixed or should I close the issue once 4.3.0 is publicly available?

**Comment by ekerwin** [comment]
Let's close it when 4.3.0 is publicly available, which should be soon.

**Comment by joc0611** [comment]
@ekerwin I think, we have to wait for a version > 4.3.0. I found I bug in my first PR. See https://github.com/blackducksoftware/hub-common/pull/230

**Comment by akamen** [comment]
@joc0611  we released 4.3.0 and 4.4.0 is code frozen and in QA now.  Is the current 4.4.0 branch useful for you?

**Comment by joc0611** [comment]
@akamen https://github.com/blackducksoftware/hub-common/pull/230 over at hub-common will eventually fix this issue. Once the resulting hub-common version is integrated in hub-detect, we can close the issue at hand I guess. 

Originally we thought we can close it with the release of 4.3.0, but my initial fix turned out to be incomplete.

**Comment by joc0611** [comment]
I guess we can close this. I successfully tested the fix with version 5.2.0
