### ISSUE TITLE
URLs are broken for recent versions of Hub

### ISSUE THREAD

**Issue by rickity-cricket** [blackducksoftware/hub-detect#359]
# Issue template

I suppose I'm not the only one to have this issue, but the valuable Black Duck URL posted into the logs fails to load the page correctly, and I'm required to workaround this problem by chopping the "/components" section of the URL.

Quite surprised this wasn't tested immediately with the new version as it's likely the first step of anyone running hub-detect.

## Expected behavior
* Click the link in the log output and see the project I just scanned to
## Actual behavior
* 
Page Not Found, but...
you've requested a valid API - Here's the output from that request.

![image](https://user-images.githubusercontent.com/19908470/49013887-1f65cb80-f176-11e8-9292-bb39ac53cbc7.png)

## Steps to Reproduce
* Run hub detect with any new version of black duck
* Click the URL in the log output
*
## Version
**Project Version:**

*
**Language Version:**

*
**OS:**

*

**Comment by akamen** [comment]
@rickity-cricket  thanks for filing this!  We will take a look.

**Comment by ekerwin** [comment]
This was a mild regression in Black Duck. It has been fixed in 2018.12. This was indeed tested immediately and resolved just as fast, but as with any commercial software product there is a lifecycle that is followed for releases. 2018.12 should be available to customers after January 2nd.
