### ISSUE TITLE
5.2.0 FAILURE_BLACKDUCK_FEATURE_ERROR

### ISSUE THREAD

**Issue by zengshengliu** [blackducksoftware/hub-detect#384]
# Issue template
## Expected behavior
* Blackduck scan completed successfully
## Actual behavior
* FAILURE_BLACKDUCK_FEATURE_ERROR on 5.2.0 (no issue with 5.1.0)
## Steps to Reproduce
* Run blackduck scan
* (scan pull down 5.2.0 version)
* FAILURE_BLACKDUCK_FEATURE_ERROR
* Detect run failed: [Black Duck Error Message]: Not found /api/current-user.
## Version
**Project Version:**
* 
**Language Version:**
* Java 8
**OS:**
* Circle CI Linux Build

**Comment by akamen** [comment]
This is likely a Hub version mismatch.  Please upgrade your instance and if this issue persists, please open a new one here:  https://github.com/blackducksoftware/synopsys-detect
