### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by omerlh** [blackducksoftware/hub-detect#55]
I would like to run this tool from docker file - it will make it easier to run it in our CI server (no need to have any dependencies installed). Are you planning to support this? I can help with a PR, if that's acceptable.

**Comment by jrichardBD** [comment]
You should be able to do this now using RUN in the docker file, does that not work for you? What is the issue when you try it?  You shouldn't need any dependencies in order to run hub-detect, or are you referring to bash and java as dependencies?

**Comment by omerlh** [comment]
I am referring to Java as a dependency (although to be honest - it is already installed on TeamCity, because TeamCity needs it). Anyway, I found docker more convenient than the current method - using bash and curl. I know this is simple - I just wanted to check if this is something you are planning to support, or should I create one myself.

**Comment by jrichardBD** [comment]
What would be creating? I'm not sure what you are asking for. Are you asking for a non java based tool?

**Comment by omerlh** [comment]
No, sorry for being unclear. All I am asking - I want to run hub detect as a docker image. Should I create this docker image (which is basically running the shell script) or do you plan to have an official docker image?

**Comment by utsavsanghani** [comment]
Omer, can we discuss this over the phone with Nick? I am not sure what the ask is here and a clarification will help. What times best for you?

**Comment by omerlh** [comment]
Sure, evening (after 8:00) could work for me next week. Thanks

**Comment by utsavsanghani** [comment]
Closing for now because of insufficient information
