### ISSUE TITLE
Collect NodeJS version

### ISSUE THREAD

**Issue by omerlh** [blackducksoftware/hub-detect#66]
You can specify the NodeJS version in the package.json file using the `engine` property. Could be useful to collect that also as a dependency, so we could also detect security issues for NodeJS.

**Comment by akamen** [comment]
@omerlh that would be a highly unorthodox thing for us to do I am afraid.  That would be similar to providing a Java version just because it is a Maven project.  Unless you are actually shipping Node itself with your product, you really would not want it on your BOM.

**Comment by omerlh** [comment]
Why not? My project has pretty strong dependency on NodeJS - which is also true for Java, ASP.Net or Nginx. If there is a vulnerability in NodeJS, my code is vulnerable. There is no difference between this and any other dependency...
